/**
 * managers/export_manager.js
 * 专职管理 PNG/Config.lua/Data.lua 导出与图层合并逻辑
 */

const TIER_ALPHA_RESTORE = {
    1: 255,
    2: 191,
    3: 128,
    4: 64,
};

export class ExportManager {
    static downloadText(filename, text) {
        const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    }

    static exportLayerAsPNG(layer) {
        if (!layer || !layer.grid || !layer.width || !layer.height) return;
        const canvas = document.createElement("canvas");
        canvas.width = layer.width;
        canvas.height = layer.height;
        const ctx = canvas.getContext("2d");
        const imgData = ctx.createImageData(layer.width, layer.height);
        const data = imgData.data;

        for (let y = 1; y <= layer.height; y++) {
            const row = layer.grid[y];
            if (!row) continue;
            for (let x = 1; x <= layer.width; x++) {
                const cell = row[x];
                const col = typeof cell === "object" ? cell?.color : cell;
                const tier = typeof cell === "object" ? (cell?.tier || 1) : 1;

                if (col && col !== "empty" && col.startsWith("#")) {
                    const hex = col.replace("#", "");
                    const r = parseInt(hex.substring(0, 2), 16) || 0;
                    const g = parseInt(hex.substring(2, 4), 16) || 0;
                    const b = parseInt(hex.substring(4, 6), 16) || 0;
                    const a = TIER_ALPHA_RESTORE[tier] !== undefined ? TIER_ALPHA_RESTORE[tier] : 255;

                    const idx = ((y - 1) * layer.width + (x - 1)) * 4;
                    data[idx] = r;
                    data[idx + 1] = g;
                    data[idx + 2] = b;
                    data[idx + 3] = a;
                }
            }
        }

        ctx.putImageData(imgData, 0, 0);
        const a = document.createElement("a");
        a.href = canvas.toDataURL("image/png");
        a.download = `${layer.name || "layer"}.png`;
        a.click();
    }

    static generateDataLuaCode(layer) {
        let dataLua = `-- Generated by Celestial Editor for: ${layer.name}\n`;
        dataLua += `local map_data = {\n`;
        dataLua += `    schema_version = 1,\n`;
        dataLua += `    coordinate_system = "pixel_grid_1based",\n`;
        dataLua += `    width = ${layer.width},\n`;
        dataLua += `    height = ${layer.height},\n`;
        dataLua += `    total_pixels = ${layer.width * layer.height},\n`;
        dataLua += `    palette = {\n`;

        const paletteMap = new Map();
        paletteMap.set("empty", 0);
        dataLua += `        [0] = nil,\n`;

        let palId = 1;
        layer.uniqueColors.forEach(c => {
            paletteMap.set(c.toLowerCase(), palId);
            dataLua += `        [${palId}] = "${c.toLowerCase()}",\n`;
            palId++;
        });
        dataLua += `    },\n`;

        let rleRuns = [];
        let lastId = null;
        let runLen = 0;

        for (let y = 1; y <= layer.height; y++) {
            for (let x = 1; x <= layer.width; x++) {
                const cell = layer.grid[y] && layer.grid[y][x];
                const col = typeof cell === "object" ? cell?.color : cell;
                const safeCol = (col && col !== "empty") ? col.toLowerCase() : "empty";
                const cid = paletteMap.has(safeCol) ? paletteMap.get(safeCol) : 0;

                if (lastId === null) {
                    lastId = cid;
                    runLen = 1;
                } else if (lastId === cid) {
                    runLen++;
                } else {
                    rleRuns.push(`${lastId}:${runLen}`);
                    lastId = cid;
                    runLen = 1;
                }
            }
        }
        if (lastId !== null) rleRuns.push(`${lastId}:${runLen}`);

        dataLua += `    rle_data = "${rleRuns.join(";")}",\n`;
        dataLua += `}\n\n`;
        dataLua += `function map_data:Unpack()\n`;
        dataLua += `    local grid = {}\n`;
        dataLua += `    for y = 1, self.height do grid[y] = {} end\n`;
        dataLua += `    local cur_x, cur_y = 1, 1\n`;
        dataLua += `    for id_str, count_str in string.gmatch(self.rle_data, "(%d+):(%d+)") do\n`;
        dataLua += `        local id, count = tonumber(id_str), tonumber(count_str)\n`;
        dataLua += `        local color = self.palette[id]\n`;
        dataLua += `        for _ = 1, count do\n`;
        dataLua += `            grid[cur_y][cur_x] = color\n`;
        dataLua += `            cur_x = cur_x + 1\n`;
        dataLua += `            if cur_x > self.width then cur_x = 1; cur_y = cur_y + 1 end\n`;
        dataLua += `        end\n`;
        dataLua += `    end\n`;
        dataLua += `    return grid\n`;
        dataLua += `end\n\nreturn map_data\n`;

        return dataLua;
    }

    static batchExport(targets, layerStack, configStore, getMergedRulesForLayer, options) {
        const { expPNG, expConfig, expData } = options;
        for (const idx of targets) {
            const cur = layerStack[idx];
            if (!cur) continue;

            if (expPNG) this.exportLayerAsPNG(cur);

            if (expConfig) {
                const mergedRules = getMergedRulesForLayer(cur);
                configStore.setRules(cur.name, mergedRules);
                const code = configStore.exportToLua(cur.name);
                this.downloadText(`config_${cur.fileBaseName}.lua`, code);
            }

            if (expData) {
                const dataCode = this.generateDataLuaCode(cur);
                this.downloadText(`${cur.fileBaseName}_data.lua`, dataCode);
            }
        }
    }

    static mergeLayers(layerStack, selectedIndices, mergeLua, getMergedRulesForLayer) {
        const sortedIndices = [...selectedIndices].sort((a, b) => a - b);
        const baseLayer = layerStack[sortedIndices[0]];
        const w = baseLayer.width;
        const h = baseLayer.height;

        const mergedGrid = Array.from({ length: h + 1 }, () => Array(w + 1).fill("empty"));
        const uniqueColorsSet = new Set();
        const mergedRules = {};

        for (const idx of sortedIndices) {
            const l = layerStack[idx];
            if (!l.grid) continue;

            for (let y = 1; y <= h; y++) {
                const row = l.grid[y];
                if (!row) continue;
                for (let x = 1; x <= w; x++) {
                    const cell = row[x];
                    const col = typeof cell === "object" ? cell?.color : cell;
                    const tier = typeof cell === "object" ? (cell?.tier || 1) : 1;

                    if (col && col !== "empty") {
                        mergedGrid[y][x] = { color: col, tier };
                        uniqueColorsSet.add(col.toLowerCase());
                    }
                }
            }

            if (mergeLua) {
                const r = getMergedRulesForLayer(l);
                for (const [colKey, conf] of Object.entries(r)) {
                    mergedRules[colKey] = conf;
                }
            }
        }

        const mergedName = `merged_${Date.now().toString().slice(-4)}`;
        return {
            newLayer: {
                id: Date.now() + "_" + Math.random(),
                name: mergedName,
                fileBaseName: mergedName,
                visible: true,
                opacity: 1.0,
                grid: mergedGrid,
                width: w,
                height: h,
                uniqueColors: Array.from(uniqueColorsSet),
                luaList: mergeLua ? [{ id: "lua_" + Date.now(), name: `config_${mergedName}.lua`, rules: mergedRules }] : []
            },
            sortedIndices
        };
    }
}