import os
import re
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from PIL import Image

DATA_SCHEMA_VERSION = 1
DATA_COORDINATE_SYSTEM = "pixel_grid_1based"
DATA_CELL_FORMAT = "color_tier"
DATA_ENCODING = "rle_palette"

# 离散 Alpha 档位区间量化 (兼容 PS 0, 7, 5, 2 快捷键)
ALPHA_TIERS = [
    (1, 235, 255, 255),  # Tier 1: PS 100% (240~255) -> 还原 255
    (2, 165, 234, 191),  # Tier 2: PS 75%  (170~239) -> 还原 191
    (3, 95, 164, 128),   # Tier 3: PS 50%  (100~169) -> 还原 128
    (4, 15, 94, 64),     # Tier 4: PS 25%  (15~99)   -> 还原 64
]

def quantize_alpha(a):
    if a < 15:
        return 0, 0
    for tier, min_a, max_a, restore_a in ALPHA_TIERS:
        if min_a <= a <= max_a:
            return tier, restore_a
    return 4, 64

def rgb_to_hex(r, g, b):
    return f"#{r:02x}{g:02x}{b:02x}"

def hex_to_rgb(hex_str):
    hex_str = hex_str.lstrip("#")
    return int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16)

def encode_image_layer(img):
    width, height = img.size
    palette_map = {("NONE", 0): 0}
    palette_list = [None]
    next_id = 1

    runs = []
    curr_id = None
    curr_len = 0

    for y in range(height):
        for x in range(width):
            r, g, b, a = img.getpixel((x, y))
            tier, _ = quantize_alpha(a)
            if tier == 0:
                key = ("NONE", 0)
            else:
                hex_color = rgb_to_hex(r, g, b)
                key = (hex_color, tier)

            if key not in palette_map:
                palette_map[key] = next_id
                palette_list.append(key)
                next_id += 1

            cid = palette_map[key]
            if cid == curr_id:
                curr_len += 1
            else:
                if curr_id is not None:
                    runs.append(f"{curr_id}:{curr_len}")
                curr_id = cid
                curr_len = 1

    if curr_id is not None:
        runs.append(f"{curr_id}:{curr_len}")

    palette_lines = ["            [0] = nil, -- 虚空 / 透明"]
    for i in range(1, len(palette_list)):
        c_hex, c_tier = palette_list[i]
        palette_lines.append(f'            [{i}] = {{ color = "{c_hex}", tier = {c_tier} }},')

    return width, height, "\n".join(palette_lines), ";".join(runs), len(palette_list) - 1

def build_single_layer_lua(width, height, palette_str, rle_string):
    return f"""-- Generated by mapgen (Single Layer)
local map_data = {{
    schema_version = {DATA_SCHEMA_VERSION},
    coordinate_system = "{DATA_COORDINATE_SYSTEM}",
    cell_format = "{DATA_CELL_FORMAT}",
    encoding = "{DATA_ENCODING}",
    width = {width},
    height = {height},
    total_pixels = {width * height},
    palette = {{
{palette_str}
    }},
    rle_data = "{rle_string}",
}}

function map_data:Unpack()
    local grid = {{}}
    for y = 1, self.height do
        grid[y] = {{}}
    end
    local cur_x, cur_y = 1, 1
    for id_str, count_str in string.gmatch(self.rle_data, "(%d+):(%d+)") do
        local id = tonumber(id_str)
        local count = tonumber(count_str)
        local item = self.palette[id]
        local cell = item and {{ color = item.color, tier = item.tier }} or nil
        for _ = 1, count do
            grid[cur_y][cur_x] = cell
            cur_x = cur_x + 1
            if cur_x > self.width then
                cur_x = 1
                cur_y = cur_y + 1
            end
        end
    end
    return grid
end

return map_data
"""

def build_blueprint_lua(width, height, layers_data):
    layer_entries = []
    for l_name, (pal_str, rle_str) in layers_data.items():
        layer_entries.append(f"""        {l_name} = {{
            palette = {{
{pal_str}
            }},
            rle_data = "{rle_str}",
        }},""")

    all_layers_str = "\n".join(layer_entries)

    return f"""-- Generated by mapgen (Dual-Layer Blueprint Package)
local blueprint_data = {{
    schema_version = {DATA_SCHEMA_VERSION},
    coordinate_system = "{DATA_COORDINATE_SYSTEM}",
    cell_format = "{DATA_CELL_FORMAT}",
    encoding = "{DATA_ENCODING}",
    width = {width},
    height = {height},
    total_pixels = {width * height},
    is_blueprint = true,
    layers = {{
{all_layers_str}
    }},
}}

function blueprint_data:Unpack()
    local result = {{}}
    for layer_name, layer_info in pairs(self.layers) do
        local grid = {{}}
        for y = 1, self.height do
            grid[y] = {{}}
        end
        local cur_x, cur_y = 1, 1
        for id_str, count_str in string.gmatch(layer_info.rle_data, "(%d+):(%d+)") do
            local id = tonumber(id_str)
            local count = tonumber(count_str)
            local item = layer_info.palette[id]
            local cell = item and {{ color = item.color, tier = item.tier }} or nil
            for _ = 1, count do
                grid[cur_y][cur_x] = cell
                cur_x = cur_x + 1
                if cur_x > self.width then
                    cur_x = 1
                    cur_y = cur_y + 1
                end
            end
        end
        result[layer_name] = grid
    end
    return result
end

return blueprint_data
"""


class _LuaDataReader:
    """只读取生成文件里的字面量数据表，不执行 Lua 代码。"""

    def __init__(self, source):
        self.source = source
        self.pos = 0

    def skip(self):
        while self.pos < len(self.source):
            if self.source[self.pos].isspace():
                self.pos += 1
            elif self.source.startswith("--", self.pos):
                block = re.match(r"--\[(=*)\[", self.source[self.pos:])
                if block:
                    end = self.source.find("]" + block.group(1) + "]", self.pos + block.end())
                    if end < 0:
                        raise ValueError("Lua 数据注释未闭合")
                    self.pos = end + len(block.group(1)) + 2
                else:
                    end = self.source.find("\n", self.pos)
                    self.pos = len(self.source) if end < 0 else end + 1
            else:
                break

    def expect(self, token):
        self.skip()
        if not self.source.startswith(token, self.pos):
            raise ValueError(f"Lua 数据格式错误：位置 {self.pos} 需要 {token}")
        self.pos += len(token)

    def value(self):
        self.skip()
        if self.pos >= len(self.source):
            raise ValueError("Lua 数据表意外结束")
        char = self.source[self.pos]
        if char == "{":
            return self.table()
        if char in ('"', "'"):
            self.pos += 1
            text = []
            while self.pos < len(self.source):
                char_next = self.source[self.pos]
                self.pos += 1
                if char_next == char:
                    return "".join(text)
                if char_next == "\\":
                    if self.pos >= len(self.source):
                        break
                    escaped = self.source[self.pos]
                    self.pos += 1
                    escapes = {"n": "\n", "r": "\r", "t": "\t", "\\": "\\", '"': '"', "'": "'"}
                    if escaped not in escapes:
                        raise ValueError("不支持的数据字符串转义")
                    char_next = escapes[escaped]
                text.append(char_next)
            raise ValueError("Lua 数据字符串未闭合")
        number = re.match(r"-?\d+(?:\.\d+)?", self.source[self.pos:])
        if number:
            self.pos += number.end()
            text = number.group(0)
            return float(text) if "." in text else int(text)
        keyword = re.match(r"(?:true|false|nil)\b", self.source[self.pos:])
        if keyword:
            self.pos += keyword.end()
            return {"true": True, "false": False, "nil": None}[keyword.group(0)]
        raise ValueError(f"不支持的 Lua 数据值，位置 {self.pos}")

    def table(self):
        self.expect("{")
        result = {}
        while True:
            self.skip()
            if self.source.startswith("}", self.pos):
                self.pos += 1
                return result
            if self.source.startswith("[", self.pos):
                self.pos += 1
                key = self.value()
                if type(key) not in (int, str):
                    raise ValueError("数据表索引必须是整数或字符串")
                self.expect("]")
            else:
                key_match = re.match(r"[A-Za-z_]\w*", self.source[self.pos:])
                if not key_match:
                    raise ValueError(f"Lua 数据表字段无效，位置 {self.pos}")
                key = key_match.group(0)
                self.pos += key_match.end()
            self.expect("=")
            if key in result:
                raise ValueError(f"Lua 数据字段重复：{key}")
            result[key] = self.value()
            self.skip()
            if self.source.startswith((",", ";"), self.pos):
                self.pos += 1
            elif not self.source.startswith("}", self.pos):
                raise ValueError("Lua 数据字段之间缺少分隔符")


def read_lua_data_table(source):
    reader = _LuaDataReader(source.lstrip("\ufeff"))
    reader.skip()
    header = re.match(r"(?:local\s+[A-Za-z_]\w*\s*=\s*|return\s+)?(?=\{)", reader.source[reader.pos:])
    if not header:
        raise ValueError("未找到支持的 Lua 地图数据表")
    reader.pos += header.end()
    return reader.table()


def decode_layer_pixels(layer, width, height, allow_legacy=True):
    if not isinstance(layer, dict) or not isinstance(layer.get("palette"), dict):
        raise ValueError("图层缺少有效的 palette")
    if type(width) is not int or type(height) is not int or width <= 0 or height <= 0:
        raise ValueError("width 和 height 必须为正整数")
    palette = {0: (0, 0, 0, 0)}
    tier_alpha = {1: 255, 2: 191, 3: 128, 4: 64}
    for idx, item in layer["palette"].items():
        if type(idx) is not int or idx < 0:
            raise ValueError("palette id 必须为非负整数")
        if idx == 0 and item is None:
            continue
        if idx == 0:
            raise ValueError("palette id 0 必须保留给透明像素")
        if isinstance(item, str) and allow_legacy:
            color, tier = item, 1
        elif isinstance(item, dict):
            color, tier = item.get("color"), item.get("tier")
        else:
            raise ValueError(f"palette id {idx} 的颜色格式无效")
        if not isinstance(color, str) or not re.fullmatch(r"#[0-9a-fA-F]{6}", color):
            raise ValueError(f"palette id {idx} 的颜色必须为 #RRGGBB")
        if type(tier) is not int or tier not in tier_alpha:
            raise ValueError(f"palette id {idx} 的 tier 必须为 1~4")
        palette[idx] = (*hex_to_rgb(color), tier_alpha[tier])
    rle = layer.get("rle_data")
    if not isinstance(rle, str) or not rle:
        raise ValueError("图层缺少有效的 rle_data")
    runs = []
    total = 0
    for pair in rle.split(";"):
        match = re.fullmatch(r"\s*(\d+):(\d+)\s*", pair)
        if not match:
            raise ValueError("RLE 数据格式错误")
        idx, count = map(int, match.groups())
        if idx not in palette:
            raise ValueError(f"RLE 引用了不存在的 palette id {idx}")
        if count <= 0:
            raise ValueError("RLE 段长度必须大于 0")
        total += count
        if total > width * height:
            raise ValueError("RLE 像素总数超过 width * height")
        runs.append((idx, count))
    if total != width * height:
        raise ValueError(f"RLE 像素总数 {total} 与 width * height {width * height} 不符")
    return [palette[idx] for idx, count in runs for _ in range(count)]


def decode_map_data(source):
    data = read_lua_data_table(source)
    version = data.get("schema_version")
    if "schema_version" in data:
        if type(version) is not int or version != DATA_SCHEMA_VERSION:
            raise ValueError(f"不支持的 schema_version：{version}")
        expected = {"coordinate_system": DATA_COORDINATE_SYSTEM,
                    "cell_format": DATA_CELL_FORMAT, "encoding": DATA_ENCODING}
        for key, value in expected.items():
            if data.get(key) != value:
                raise ValueError(f"不支持的 {key}：{data.get(key)}")
    width, height = data.get("width"), data.get("height")
    if type(width) is not int or type(height) is not int or width <= 0 or height <= 0:
        raise ValueError("width 和 height 必须为正整数")
    if "total_pixels" in data and (type(data["total_pixels"]) is not int
                                  or data["total_pixels"] != width * height):
        raise ValueError("total_pixels 与 width * height 不符")
    is_blueprint = data.get("is_blueprint") is True
    layers = data.get("layers") if is_blueprint else {"": data}
    if not isinstance(layers, dict) or not layers:
        raise ValueError("蓝图缺少有效的 layers")
    decoded = {}
    for name, layer in layers.items():
        if is_blueprint and name not in ("ground", "prefab", "perfab"):
            raise ValueError(f"不支持的蓝图图层：{name}")
        decoded[name] = decode_layer_pixels(layer, width, height, allow_legacy=version is None)
    return width, height, is_blueprint, decoded


class MapGenApp:
    def __init__(self, root):
        self.root = root
        self.root.title("DST 像素地图 / 蓝图双层解析转换器")
        self.root.geometry("720x580")
        self.root.resizable(False, False)

        notebook = ttk.Notebook(self.root)
        notebook.pack(fill="both", expand=True, padx=10, pady=10)

        tab_bp = ttk.Frame(notebook)
        tab_batch = ttk.Frame(notebook)
        tab_restore = ttk.Frame(notebook)

        notebook.add(tab_bp, text="蓝图合并打包 (专属页面)")
        notebook.add(tab_batch, text="普通图层多选批量打包")
        notebook.add(tab_restore, text="Lua 逆向还原 PNG")

        self.setup_blueprint_tab(tab_bp)
        self.setup_batch_tab(tab_batch)
        self.setup_restore_tab(tab_restore)

    def setup_blueprint_tab(self, parent):
        frame = ttk.LabelFrame(parent, text="蓝图双层自动配对打包 (识别 _ground 与 _prefab / _perfab)", padding=10)
        frame.pack(fill="both", expand=True, padx=10, pady=10)

        ttk.Label(frame, text="操作说明：点击下方按钮，使用 Ctrl 或 Shift 连选所有蓝图 PNG 文件。").pack(anchor="w", pady=2)
        ttk.Label(frame, text="工具将按前缀自动寻找同一蓝图的 _ground 与 _prefab 层并合并导出。").pack(anchor="w", pady=2)

        btn_box = ttk.Frame(frame)
        btn_box.pack(fill="x", pady=6)
        ttk.Button(btn_box, text="选择蓝图 PNG 文件 (支持连选)...", command=self.select_bp_files).pack(side="left", padx=4)
        ttk.Button(btn_box, text="清空列表", command=self.clear_bp_files).pack(side="left", padx=4)

        self.bp_listbox = tk.Listbox(frame, height=9, selectmode="extended")
        self.bp_listbox.pack(fill="x", padx=4, pady=4)

        out_box = ttk.Frame(frame)
        out_box.pack(fill="x", pady=4)
        ttk.Label(out_box, text="输出目录:").pack(side="left", padx=4)
        self.bp_out_entry = ttk.Entry(out_box, width=54)
        self.bp_out_entry.pack(side="left", padx=4)
        ttk.Button(out_box, text="更改...", command=self.select_bp_output_dir).pack(side="left", padx=4)

        ttk.Button(frame, text="开始合并打包选中蓝图", command=self.process_blueprints).pack(pady=8)

        self.bp_log = tk.Text(frame, height=8, state="disabled", wrap="word")
        self.bp_log.pack(fill="both", expand=True, padx=4, pady=4)

    def setup_batch_tab(self, parent):
        frame = ttk.LabelFrame(parent, text="通用独立图层批量打包 (连选文件独立输出)", padding=10)
        frame.pack(fill="both", expand=True, padx=10, pady=10)

        btn_box = ttk.Frame(frame)
        btn_box.pack(fill="x", pady=4)
        ttk.Button(btn_box, text="连选 PNG 文件 (Ctrl/Shift)...", command=self.select_batch_files).pack(side="left", padx=4)
        ttk.Button(btn_box, text="清空", command=self.clear_batch_files).pack(side="left", padx=4)

        self.batch_listbox = tk.Listbox(frame, height=9, selectmode="extended")
        self.batch_listbox.pack(fill="x", padx=4, pady=4)

        out_box = ttk.Frame(frame)
        out_box.pack(fill="x", pady=4)
        ttk.Label(out_box, text="输出目录:").pack(side="left", padx=4)
        self.batch_out_entry = ttk.Entry(out_box, width=54)
        self.batch_out_entry.pack(side="left", padx=4)
        ttk.Button(out_box, text="更改...", command=self.select_batch_output_dir).pack(side="left", padx=4)

        ttk.Button(frame, text="一键独立批量导出 Lua", command=self.process_batch).pack(pady=8)

        self.batch_log = tk.Text(frame, height=8, state="disabled", wrap="word")
        self.batch_log.pack(fill="both", expand=True, padx=4, pady=4)

    def setup_restore_tab(self, parent):
        frame = ttk.LabelFrame(parent, text="Lua 逆向还原 PNG (支持普通图层与双层蓝图)", padding=10)
        frame.pack(fill="both", expand=True, padx=10, pady=10)

        btn_box = ttk.Frame(frame)
        btn_box.pack(fill="x", pady=4)
        ttk.Button(btn_box, text="连选 Lua 数据文件 (Ctrl/Shift)...", command=self.select_restore_files).pack(side="left", padx=4)
        ttk.Button(btn_box, text="清空", command=self.clear_restore_files).pack(side="left", padx=4)

        self.restore_listbox = tk.Listbox(frame, height=9, selectmode="extended")
        self.restore_listbox.pack(fill="x", padx=4, pady=4)

        ttk.Button(frame, text="开始逆向还原 PNG", command=self.process_restore).pack(pady=8)

        self.restore_log = tk.Text(frame, height=8, state="disabled", wrap="word")
        self.restore_log.pack(fill="both", expand=True, padx=4, pady=4)

    def log(self, text_widget, msg):
        text_widget.config(state="normal")
        text_widget.insert(tk.END, msg + "\n")
        text_widget.see(tk.END)
        text_widget.config(state="disabled")

    def select_bp_files(self):
        files = filedialog.askopenfilenames(filetypes=[("PNG 图片", "*.png")])
        if files:
            for f in files:
                if f not in self.bp_listbox.get(0, tk.END):
                    self.bp_listbox.insert(tk.END, f)
            if not self.bp_out_entry.get():
                self.bp_out_entry.insert(0, os.path.dirname(files[0]))

    def clear_bp_files(self):
        self.bp_listbox.delete(0, tk.END)

    def select_bp_output_dir(self):
        d = filedialog.askdirectory()
        if d:
            self.bp_out_entry.delete(0, tk.END)
            self.bp_out_entry.insert(0, d)

    def process_blueprints(self):
        files = self.bp_listbox.get(0, tk.END)
        out_dir = self.bp_out_entry.get().strip()
        if not files or not out_dir:
            messagebox.showwarning("提示", "请选择蓝图 PNG 文件及输出目录！")
            return

        groups = {}
        for path in files:
            fname = os.path.basename(path)
            stem, _ = os.path.splitext(fname)
            m = re.match(r"^(?P<base>.+?)_(?P<layer>ground|prefab|perfab)$", stem, re.IGNORECASE)
            if m:
                base = m.group("base")
                layer_type = m.group("layer").lower()
                if layer_type == "perfab":
                    layer_type = "prefab"
                groups.setdefault(base, {})[layer_type] = path
            else:
                self.log(self.bp_log, f"[跳过] 无法识别的蓝图后缀: {fname} (请以 _ground 或 _prefab 结尾)")

        for base_name, layers in groups.items():
            try:
                layers_data = {}
                common_w, common_h = None, None

                for l_type, l_path in layers.items():
                    img = Image.open(l_path).convert("RGBA")
                    w, h, pal_str, rle_str, p_cnt = encode_image_layer(img)
                    if common_w is None:
                        common_w, common_h = w, h
                    elif (common_w, common_h) != (w, h):
                        raise ValueError(f"蓝图图层尺寸不一致: {base_name} ({common_w}x{common_h} vs {w}x{h})")
                    layers_data[l_type] = (pal_str, rle_str)

                out_filename = f"bp_{base_name}_data.lua"
                out_path = os.path.join(out_dir, out_filename)
                lua_src = build_blueprint_lua(common_w, common_h, layers_data)

                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(lua_src)

                self.log(self.bp_log, f"[成功打包蓝图] {out_filename} (包含图层: {', '.join(layers.keys())})")
            except Exception as e:
                self.log(self.bp_log, f"[错误] 蓝图 {base_name} 打包失败: {e}")

        messagebox.showinfo("完成", "蓝图打包处理完毕！")

    def select_batch_files(self):
        files = filedialog.askopenfilenames(filetypes=[("PNG 图片", "*.png")])
        if files:
            for f in files:
                if f not in self.batch_listbox.get(0, tk.END):
                    self.batch_listbox.insert(tk.END, f)
            if not self.batch_out_entry.get():
                self.batch_out_entry.insert(0, os.path.dirname(files[0]))

    def clear_batch_files(self):
        self.batch_listbox.delete(0, tk.END)

    def select_batch_output_dir(self):
        d = filedialog.askdirectory()
        if d:
            self.batch_out_entry.delete(0, tk.END)
            self.batch_out_entry.insert(0, d)

    def process_batch(self):
        files = self.batch_listbox.get(0, tk.END)
        out_dir = self.batch_out_entry.get().strip()
        if not files or not out_dir:
            messagebox.showwarning("提示", "请选择普通 PNG 文件及输出目录！")
            return

        for path in files:
            try:
                img = Image.open(path).convert("RGBA")
                w, h, pal_str, rle_str, p_cnt = encode_image_layer(img)
                lua_content = build_single_layer_lua(w, h, pal_str, rle_str)

                fname = os.path.basename(path)
                stem, _ = os.path.splitext(fname)
                out_path = os.path.join(out_dir, f"{stem}_data.lua")

                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(lua_content)

                self.log(self.batch_log, f"[成功] {fname} -> {os.path.basename(out_path)} ({w}x{h})")
            except Exception as e:
                self.log(self.batch_log, f"[失败] 转换 {path} 异常: {e}")

        messagebox.showinfo("完成", "普通图层批量转换完毕！")

    def select_restore_files(self):
        files = filedialog.askopenfilenames(filetypes=[("Lua 文件", "*.lua")])
        if files:
            for f in files:
                if f not in self.restore_listbox.get(0, tk.END):
                    self.restore_listbox.insert(tk.END, f)

    def clear_restore_files(self):
        self.restore_listbox.delete(0, tk.END)

    def restore_layer(self, content_block, w, h, out_png):
        layer = content_block if isinstance(content_block, dict) else read_lua_data_table(content_block)
        pixels = decode_layer_pixels(layer, w, h)
        img = Image.new("RGBA", (w, h))
        img.putdata(pixels)
        img.save(out_png)
        return True

    def process_restore(self):
        files = self.restore_listbox.get(0, tk.END)
        if not files:
            messagebox.showwarning("提示", "请选择需要逆向还原的 Lua 文件！")
            return

        success_count, failure_count = 0, 0
        for path in files:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    src = f.read()

                w, h, is_blueprint, layers = decode_map_data(src)

                dname = os.path.dirname(path)
                bname = os.path.splitext(os.path.basename(path))[0].replace("_data", "")

                for name, pixels in layers.items():
                    suffix = f"_{name}" if is_blueprint else ""
                    out_png = os.path.join(dname, f"{bname}{suffix}_restore.png")
                    img = Image.new("RGBA", (w, h))
                    img.putdata(pixels)
                    img.save(out_png)
                    success_count += 1
                    self.log(self.restore_log, f"[还原成功] {out_png}")
            except Exception as e:
                failure_count += 1
                self.log(self.restore_log, f"[还原失败] {path}: {e}")

        summary = f"已还原 {success_count} 张 PNG，失败 {failure_count} 个文件。"
        if failure_count:
            messagebox.showwarning("还原结果", summary)
        else:
            messagebox.showinfo("完成", summary)

if __name__ == "__main__":
    root = tk.Tk()
    app = MapGenApp(root)
    root.mainloop()
